//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovieCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDatabaseEntities : DbContext
    {
        public MovieDatabaseEntities()
            : base("name=MovieDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<ProductionCompany> ProductionCompanies { get; set; }
        public virtual DbSet<ProductionCountry> ProductionCountries { get; set; }
        public virtual DbSet<SpokenLanguage> SpokenLanguages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
