//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovieCollection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProductionCompanyMetaData))]
    public partial class ProductionCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionCompany()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public string description { get; set; }
        public string headquarters { get; set; }
        public string homepage { get; set; }
        public int id { get; set; }
        public string logo_path { get; set; }
        public string name { get; set; }
        public string origin_country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }
    }

    public class ProductionCompanyMetaData
    {
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Headquarters")]
        public string headquarters { get; set; }
        [Display(Name = "Homepage")]
        public string homepage { get; set; }
        [Display(Name = "ID")]
        public int id { get; set; }
        [Display(Name = "Logo Path")]
        public string logo_path { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Origin Country")]
        public string origin_country { get; set; }
    }
}
